-- =====================================================================
-- MODULO 4: DEVOLUCIONES A PROVEEDORES Y LIQUIDACION  (Integrante 4)
-- Proyecto: Sistema Drogueria FARMATODO
-- Ejecutar en: Supabase > SQL Editor > New query > Run
-- Depende de las tablas existentes: tiendas, usuarios, lotes
-- (todas con llaves primarias de tipo integer)
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) PROVEEDORES
-- Guarda los datos del proveedor y la politica de devolucion del
-- fabricante (si acepta canje, nota de credito y con cuanta anticipacion).
-- ---------------------------------------------------------------------
create table if not exists proveedores (
    id_proveedor              integer generated by default as identity primary key,
    nombre                    varchar(150) not null,
    contacto                  varchar(100),
    telefono                  varchar(30),
    correo                    varchar(150),
    acepta_canje              boolean      not null default true,
    acepta_nota_credito       boolean      not null default true,
    dias_min_antes_vencimiento integer     not null default 0
                              check (dias_min_antes_vencimiento >= 0),
    politica_devolucion       text,
    activo                    boolean      not null default true,
    fecha_creacion            timestamp    not null default now()
);


-- ---------------------------------------------------------------------
-- 2) DEVOLUCIONES (encabezado del tramite)
-- Una fila por cada tramite de devolucion con un proveedor.
-- ---------------------------------------------------------------------
create table if not exists devoluciones (
    id_devolucion    integer generated by default as identity primary key,
    id_tienda        integer      not null references tiendas(id_tienda),
    id_proveedor     integer      not null references proveedores(id_proveedor),
    id_usuario       integer      references usuarios(id_usuario),  -- quien lo registro
    fecha_retiro     date         not null default current_date,    -- retiro del anaquel
    estado           varchar(20)  not null default 'En revisión'
                     check (estado in ('En revisión', 'Aceptado', 'Rechazado')),
    resultado        varchar(20)
                     check (resultado in ('Canje', 'Nota de crédito')),  -- se llena al resolver
    monto_liquidado  numeric(12,2) not null default 0
                     check (monto_liquidado >= 0),
    numero_documento varchar(50),      -- No. de nota de credito o de canje
    fecha_resolucion date,
    observaciones    text,
    fecha_creacion   timestamp    not null default now()
);


-- ---------------------------------------------------------------------
-- 3) DEVOLUCION_DETALLE (que lotes y cuantas unidades se devuelven)
-- Si se borra una devolucion, se borran tambien sus lineas.
-- ---------------------------------------------------------------------
create table if not exists devolucion_detalle (
    id_detalle      integer generated by default as identity primary key,
    id_devolucion   integer      not null references devoluciones(id_devolucion) on delete cascade,
    id_lote         integer      not null references lotes(id_lote),
    cantidad        integer      not null check (cantidad > 0),
    costo_unitario  numeric(10,2) not null default 0 check (costo_unitario >= 0),
    motivo          varchar(30)  not null default 'Próximo a vencer'
                    check (motivo in ('Próximo a vencer', 'Vencido', 'Dañado', 'Otro'))
);


-- ---------------------------------------------------------------------
-- 4) HISTORIAL_LIQUIDACIONES (bitacora auditable)
-- Cada cambio de estado de una devolucion queda registrado aqui.
-- ---------------------------------------------------------------------
create table if not exists historial_liquidaciones (
    id_historial     integer generated by default as identity primary key,
    id_devolucion    integer      not null references devoluciones(id_devolucion) on delete cascade,
    id_usuario       integer      references usuarios(id_usuario),
    estado_anterior  varchar(20),
    estado_nuevo     varchar(20)  not null,
    comentario       text,
    fecha_cambio     timestamp    not null default now()
);


-- ---------------------------------------------------------------------
-- INDICES (hacen mas rapidas las consultas por tienda, proveedor, etc.)
-- ---------------------------------------------------------------------
create index if not exists idx_devoluciones_tienda    on devoluciones(id_tienda);
create index if not exists idx_devoluciones_proveedor on devoluciones(id_proveedor);
create index if not exists idx_devoluciones_estado    on devoluciones(estado);
create index if not exists idx_detalle_devolucion     on devolucion_detalle(id_devolucion);
create index if not exists idx_detalle_lote           on devolucion_detalle(id_lote);
create index if not exists idx_historial_devolucion   on historial_liquidaciones(id_devolucion);


-- ---------------------------------------------------------------------
-- TRIGGER DE AUDITORIA
-- Registra automaticamente en el historial: la creacion de una
-- devolucion y cada vez que cambia su estado.
-- ---------------------------------------------------------------------
create or replace function registrar_historial_devolucion()
returns trigger as $$
begin
    if (tg_op = 'INSERT') then
        insert into historial_liquidaciones
            (id_devolucion, id_usuario, estado_anterior, estado_nuevo, comentario)
        values
            (new.id_devolucion, new.id_usuario, null, new.estado, 'Devolución registrada');
    elsif (tg_op = 'UPDATE' and new.estado is distinct from old.estado) then
        insert into historial_liquidaciones
            (id_devolucion, id_usuario, estado_anterior, estado_nuevo, comentario)
        values
            (new.id_devolucion, new.id_usuario, old.estado, new.estado, 'Cambio de estado');
    end if;
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_historial_devolucion on devoluciones;
create trigger trg_historial_devolucion
after insert or update on devoluciones
for each row execute function registrar_historial_devolucion();


-- ---------------------------------------------------------------------
-- DATOS DE PRUEBA (OPCIONAL)
-- Quita los "--" del bloque de abajo si quieres un proveedor de ejemplo.
-- Ejecutalo UNA sola vez para no duplicar.
-- ---------------------------------------------------------------------
-- insert into proveedores
--     (nombre, contacto, telefono, correo, acepta_canje, acepta_nota_credito,
--      dias_min_antes_vencimiento, politica_devolucion)
-- values
--     ('Proveedor de Prueba S.A.', 'Juan Pérez', '5555-0000', 'ventas@prueba.com',
--      true, true, 90, 'Acepta devolución hasta 90 días antes del vencimiento.');
